### ISSUE TITLE
UTF-8 not supported ??

### ISSUE THREAD

**Issue by matsekberg** [holgerlembke/ESPxWebFlMgr#10]
I try to edit a file and insert the ° character and it is not correct handled. After edit/save/load it has become a Â°

**Comment by holgerlembke** [comment]
You are right, I didn't build in support for UTF-8.

As far as I see, the <textarea> I use does not support UTF-8 out of the box. So it would need to add some infrastructure to load and save UTF-8. And some solution to turn UTF-8 support on/off, because you might want to save files without UTF-8...

I'm not sure whether I see the entire complexity of this problem.

At least named chars should work.

**Comment by matsekberg** [comment]
Tried  `<form accept-charset="utf-8" />` ?
Or `<meta http-equiv="Content-Type" content="text/html; charset=utf-8">` ?
Or `<form method="post" action="/Subtitlor/edit" accept-charset="UTF-8">` ?

**Comment by holgerlembke** [comment]
Just added/fixed the utf8 handling in https://github.com/holgerlembke/ESPFMfGK

So far the cycle edit->save->edit->save did not destroy anything. But I'm still not sure to understand all the limits...

**Comment by holgerlembke** [comment]
Now live.
